# Generated by Django 4.2.7 on 2025-11-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('weekday', models.CharField(max_length=3)),
                ('period', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_class', models.CharField(blank=True, max_length=50)),
                ('students_json', models.TextField()),
                ('offer_type', models.CharField(choices=[('sport', 'Sport'), ('games', 'Spiele'), ('outdoor', 'Outdoor'), ('other', 'Sonstiges')], max_length=10)),
                ('offer_label', models.CharField(max_length=100)),
                ('calendar_event_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportoase_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sportoase_bookings',
                'ordering': ['-date', 'period'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Mon', 'Montag'), ('Tue', 'Dienstag'), ('Wed', 'Mittwoch'), ('Thu', 'Donnerstag'), ('Fri', 'Freitag')], max_length=3)),
                ('period', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_students', models.IntegerField(default=200)),
            ],
            options={
                'db_table': 'sportoase_timeslots',
                'ordering': ['weekday', 'period'],
                'unique_together': {('weekday', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_booking', 'Neue Buchung'), ('booking_updated', 'Buchung aktualisiert'), ('booking_deleted', 'Buchung gelöscht'), ('slot_blocked', 'Slot blockiert')], max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata_json', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='backend.booking')),
            ],
            options={
                'db_table': 'sportoase_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('weekday', models.CharField(max_length=3)),
                ('period', models.IntegerField()),
                ('reason', models.CharField(default='Beratung', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportoase_blocked_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sportoase_blocked_slots',
                'ordering': ['-date', 'period'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'period'], name='sportoase_b_date_feaf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['teacher'], name='sportoase_b_teacher_878f77_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedslot',
            index=models.Index(fields=['date', 'period'], name='sportoase_b_date_7af2f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockedslot',
            unique_together={('date', 'period')},
        ),
    ]
